name: CI (lightweight tests)

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Install minimal test dependencies
        run: |
          uv pip install pytest==8.2.2 fastapi httpx
      - name: Run pytest (chat_proxy + model_loader)
        env:
          PYTHONPATH: ${{ github.workspace }}/src
          REQUIRE_CUDA: "0"
        run: |
          uv run pytest -q tests/chat_proxy tests/model_loader
