name: Tests

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - color_narrator
          - mono
          - personal_tagger
          - vision
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Sync dependencies
        run: uv sync

      - name: Run pytest (${{ matrix.target }})
        run: uv run --with "pytest==8.2.2" pytest tests/${{ matrix.target }}
